alphabet = {
    'а': 'a',
    'б': 'b',
    'в': 'v',
    'г': 'g',
    'д': 'd',
    'е': 'e',
    'ё': 'jo',
    'ж': 'zh',
    'з': 'z',
    'и': 'i',
    'й': 'j',
    'к': 'k',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'о': 'o',
    'п': 'p',
    'р': 'r',
    'с': 's',
    'т': 't',
    'у': 'u',
    'ф': 'f',
    'х': 'h',
    'ц': 'c',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'shh',
    'ъ': '*',
    'ы': 'y',
    'ь': "'",
    'э': 'je',
    'ю': 'ju',
    'я': 'ya',
    'А': 'A',
    'Б': 'B',
    'В': 'V',
    'Г': 'G',
    'Д': 'D',
    'Е': 'E',
    'Ё': 'Jo',
    'Ж': 'Zh',
    'З': 'Z',
    'И': 'I',
    'Й': 'J',
    'К': 'K',
    'Л': 'L',
    'М': 'M',
    'Н': 'N',
    'О': 'O',
    'П': 'P',
    'Р': 'R',
    'С': 'S',
    'Т': 'T',
    'У': 'U',
    'Ф': 'F',
    'Х': 'H',
    'Ц': 'C',
    'Ч': 'Ch',
    'Ш': 'Sh',
    'Щ': 'Shh',
    'Ъ': '*',
    'Ы': 'Y',
    'Ь': "'",
    'Э': 'Je',
    'Ю': 'Ju',
    'Я': 'Ya',
}

with open('cyrillic.txt', mode='r', encoding='utf-8') as cyrillic, \
     open('transliteration.txt', mode='w', encoding='utf-8') as transliteration:
    text = [line for line in cyrillic]
    new_text = ''

    for key, value in alphabet.items():
        if key in text[0]:
            text[0] = text[0].replace(key, value)

    for row in text:
        transliteration.write(row)
